import type { Service, ServiceCategory } from "./types";

export const serviceCategories: ServiceCategory[] = [
  { slug: "ai-assistants", name: "AI Assistants & Chatbots", description: "Conversational AI assistants and large language model chat apps." },
  { slug: "ai-writing", name: "AI Writing & Content", description: "AI copywriters, editors and content generation tools." },
  { slug: "ai-image", name: "AI Image & Art", description: "Generate, edit and upscale images with AI." },
  { slug: "ai-video-audio", name: "AI Video & Audio", description: "AI video creation, avatars, voice and audio tools." },
  { slug: "design", name: "Design & Creative", description: "Graphic design, UI design and illustration tools." },
  { slug: "stock-media", name: "Stock Photos & Media", description: "Free and premium photos, video, icons and music." },
  { slug: "productivity", name: "Productivity & Docs", description: "Notes, documents and knowledge management apps." },
  { slug: "project-management", name: "Project Management", description: "Task, project and team workflow tools." },
  { slug: "pdf-tools", name: "PDF & File Tools", description: "Other online PDF and file-conversion services." },
  { slug: "dev-platforms", name: "Developer Platforms", description: "Hosting, databases, APIs and developer tooling." },
  { slug: "no-code", name: "No-Code & Site Builders", description: "Build sites and apps without writing code." },
  { slug: "marketing-email", name: "Marketing & Email", description: "Email marketing, social scheduling and growth tools." },
  { slug: "seo-analytics", name: "SEO & Analytics", description: "Keyword research, audits and web analytics." },
  { slug: "forms-surveys", name: "Forms & Surveys", description: "Build forms, surveys and collect responses." },
  { slug: "scheduling-comms", name: "Scheduling & Communication", description: "Calendars, meetings, chat and phone tools." },
  { slug: "storage-sharing", name: "Storage & File Sharing", description: "Cloud storage and large-file transfer services." },
  { slug: "finance-commerce", name: "Finance & Commerce", description: "Payments, invoicing, accounting and e-commerce." },
];

const s = (svc: Service): Service => svc;

export const services: Service[] = [
  // ─────────────── AI Assistants & Chatbots ───────────────
  s({ slug: "chatgpt", name: "ChatGPT", url: "https://chat.openai.com", category: "ai-assistants", description: "OpenAI's conversational AI assistant.", pricing: "freemium" }),
  s({ slug: "claude", name: "Claude", url: "https://claude.ai", category: "ai-assistants", description: "Anthropic's helpful, capable AI assistant.", pricing: "freemium" }),
  s({ slug: "gemini", name: "Google Gemini", url: "https://gemini.google.com", category: "ai-assistants", description: "Google's multimodal AI assistant.", pricing: "freemium" }),
  s({ slug: "microsoft-copilot", name: "Microsoft Copilot", url: "https://copilot.microsoft.com", category: "ai-assistants", description: "Microsoft's AI companion across apps.", pricing: "freemium" }),
  s({ slug: "perplexity", name: "Perplexity", url: "https://www.perplexity.ai", category: "ai-assistants", description: "AI answer engine with cited sources.", pricing: "freemium" }),
  s({ slug: "poe", name: "Poe", url: "https://poe.com", category: "ai-assistants", description: "Chat with many AI models in one app.", pricing: "freemium" }),
  s({ slug: "mistral-le-chat", name: "Mistral Le Chat", url: "https://chat.mistral.ai", category: "ai-assistants", description: "Mistral AI's fast chat assistant.", pricing: "freemium" }),
  s({ slug: "meta-ai", name: "Meta AI", url: "https://www.meta.ai", category: "ai-assistants", description: "Meta's Llama-powered assistant.", pricing: "free" }),
  s({ slug: "grok", name: "Grok", url: "https://grok.com", category: "ai-assistants", description: "xAI's conversational assistant.", pricing: "freemium" }),
  s({ slug: "deepseek", name: "DeepSeek", url: "https://chat.deepseek.com", category: "ai-assistants", description: "Open reasoning-focused AI chat.", pricing: "freemium" }),
  s({ slug: "qwen-chat", name: "Qwen Chat", url: "https://chat.qwen.ai", category: "ai-assistants", description: "Alibaba's Qwen model chat.", pricing: "free" }),
  s({ slug: "huggingface-chat", name: "HuggingChat", url: "https://huggingface.co/chat", category: "ai-assistants", description: "Open-source model chat by Hugging Face.", pricing: "free" }),
  s({ slug: "character-ai", name: "Character.AI", url: "https://character.ai", category: "ai-assistants", description: "Chat with AI characters and personas.", pricing: "freemium" }),
  s({ slug: "pi-ai", name: "Pi", url: "https://pi.ai", category: "ai-assistants", description: "Personal, supportive AI companion.", pricing: "free" }),
  s({ slug: "you-com", name: "You.com", url: "https://you.com", category: "ai-assistants", description: "AI search and assistant.", pricing: "freemium" }),
  s({ slug: "phind", name: "Phind", url: "https://www.phind.com", category: "ai-assistants", description: "AI answer engine for developers.", pricing: "freemium" }),
  s({ slug: "cohere", name: "Cohere", url: "https://cohere.com", category: "ai-assistants", description: "Enterprise LLM platform and APIs.", pricing: "paid" }),
  s({ slug: "together-ai", name: "Together AI", url: "https://www.together.ai", category: "ai-assistants", description: "Run and fine-tune open models.", pricing: "paid" }),
  s({ slug: "groq", name: "Groq", url: "https://groq.com", category: "ai-assistants", description: "Ultra-fast LLM inference.", pricing: "freemium" }),
  s({ slug: "fireworks-ai", name: "Fireworks AI", url: "https://fireworks.ai", category: "ai-assistants", description: "Fast inference for open models.", pricing: "paid" }),
  s({ slug: "openrouter", name: "OpenRouter", url: "https://openrouter.ai", category: "ai-assistants", description: "One API for many LLMs.", pricing: "freemium" }),
  s({ slug: "ollama", name: "Ollama", url: "https://ollama.com", category: "ai-assistants", description: "Run LLMs locally on your machine.", pricing: "free" }),
  s({ slug: "lm-studio", name: "LM Studio", url: "https://lmstudio.ai", category: "ai-assistants", description: "Desktop app to run local LLMs.", pricing: "free" }),
  s({ slug: "jan-ai", name: "Jan", url: "https://jan.ai", category: "ai-assistants", description: "Open-source offline AI assistant.", pricing: "free" }),
  s({ slug: "openai-platform", name: "OpenAI Platform", url: "https://platform.openai.com", category: "ai-assistants", description: "OpenAI developer APIs and tools.", pricing: "paid" }),
  s({ slug: "anthropic-console", name: "Anthropic Console", url: "https://console.anthropic.com", category: "ai-assistants", description: "Build with the Claude API.", pricing: "paid" }),
  s({ slug: "google-ai-studio", name: "Google AI Studio", url: "https://aistudio.google.com", category: "ai-assistants", description: "Prototype with Gemini models.", pricing: "freemium" }),
  s({ slug: "replicate", name: "Replicate", url: "https://replicate.com", category: "ai-assistants", description: "Run open ML models via API.", pricing: "paid" }),
  s({ slug: "gpt4all", name: "GPT4All", url: "https://www.nomic.ai/gpt4all", category: "ai-assistants", description: "Private local chatbot ecosystem.", pricing: "free" }),
  s({ slug: "deepai", name: "DeepAI", url: "https://deepai.org", category: "ai-assistants", description: "AI chat and generation tools.", pricing: "freemium" }),

  // ─────────────── AI Writing & Content ───────────────
  s({ slug: "jasper", name: "Jasper", url: "https://www.jasper.ai", category: "ai-writing", description: "AI content platform for marketing teams.", pricing: "paid" }),
  s({ slug: "copy-ai", name: "Copy.ai", url: "https://www.copy.ai", category: "ai-writing", description: "AI copywriter for sales and marketing.", pricing: "freemium" }),
  s({ slug: "writesonic", name: "Writesonic", url: "https://writesonic.com", category: "ai-writing", description: "AI writing and SEO content tool.", pricing: "freemium" }),
  s({ slug: "rytr", name: "Rytr", url: "https://rytr.me", category: "ai-writing", description: "Affordable AI writing assistant.", pricing: "freemium" }),
  s({ slug: "sudowrite", name: "Sudowrite", url: "https://www.sudowrite.com", category: "ai-writing", description: "AI tool for fiction writers.", pricing: "paid" }),
  s({ slug: "notion-ai", name: "Notion AI", url: "https://www.notion.so/product/ai", category: "ai-writing", description: "AI writing built into Notion.", pricing: "paid" }),
  s({ slug: "grammarly", name: "Grammarly", url: "https://www.grammarly.com", category: "ai-writing", description: "Grammar, spelling and tone checker.", pricing: "freemium" }),
  s({ slug: "prowritingaid", name: "ProWritingAid", url: "https://prowritingaid.com", category: "ai-writing", description: "Style and grammar editor for writers.", pricing: "freemium" }),
  s({ slug: "quillbot", name: "QuillBot", url: "https://quillbot.com", category: "ai-writing", description: "Paraphrasing and summarizing tool.", pricing: "freemium" }),
  s({ slug: "wordtune", name: "Wordtune", url: "https://www.wordtune.com", category: "ai-writing", description: "AI rewriter and editor.", pricing: "freemium" }),
  s({ slug: "hemingway", name: "Hemingway Editor", url: "https://hemingwayapp.com", category: "ai-writing", description: "Makes your writing bold and clear.", pricing: "freemium" }),
  s({ slug: "anyword", name: "Anyword", url: "https://anyword.com", category: "ai-writing", description: "Performance-driven AI copywriting.", pricing: "paid" }),
  s({ slug: "frase", name: "Frase", url: "https://www.frase.io", category: "ai-writing", description: "AI SEO content research and writing.", pricing: "paid" }),
  s({ slug: "surfer-seo", name: "Surfer SEO", url: "https://surferseo.com", category: "ai-writing", description: "Content optimization for search.", pricing: "paid" }),
  s({ slug: "scalenut", name: "Scalenut", url: "https://www.scalenut.com", category: "ai-writing", description: "AI SEO and content marketing.", pricing: "paid" }),
  s({ slug: "writer-com", name: "Writer", url: "https://writer.com", category: "ai-writing", description: "Generative AI for enterprises.", pricing: "paid" }),
  s({ slug: "lex", name: "Lex", url: "https://lex.page", category: "ai-writing", description: "AI-assisted writing document editor.", pricing: "freemium" }),
  s({ slug: "hyperwrite", name: "HyperWrite", url: "https://www.hyperwriteai.com", category: "ai-writing", description: "Personal AI writing assistant.", pricing: "freemium" }),
  s({ slug: "compose-ai", name: "Compose AI", url: "https://www.compose.ai", category: "ai-writing", description: "Autocomplete and AI writing for Chrome.", pricing: "freemium" }),
  s({ slug: "simplified", name: "Simplified", url: "https://simplified.com", category: "ai-writing", description: "All-in-one content and design suite.", pricing: "freemium" }),
  s({ slug: "gravitywrite", name: "GravityWrite", url: "https://gravitywrite.com", category: "ai-writing", description: "AI content generator for creators.", pricing: "freemium" }),
  s({ slug: "neuroflash", name: "Neuroflash", url: "https://neuroflash.com", category: "ai-writing", description: "AI text and image content tool.", pricing: "freemium" }),
  s({ slug: "contentbot", name: "ContentBot", url: "https://contentbot.ai", category: "ai-writing", description: "AI content automation for marketers.", pricing: "paid" }),
  s({ slug: "peppertype", name: "Peppertype", url: "https://www.peppercontent.io", category: "ai-writing", description: "AI content creation assistant.", pricing: "paid" }),
  s({ slug: "deepl-write", name: "DeepL Write", url: "https://www.deepl.com/write", category: "ai-writing", description: "AI-powered writing improvement.", pricing: "freemium" }),
  s({ slug: "deepl-translate", name: "DeepL Translator", url: "https://www.deepl.com", category: "ai-writing", description: "High-quality machine translation.", pricing: "freemium" }),
  s({ slug: "languagetool", name: "LanguageTool", url: "https://languagetool.org", category: "ai-writing", description: "Open-source grammar checker.", pricing: "freemium" }),
  s({ slug: "wordhippo", name: "WordHippo", url: "https://www.wordhippo.com", category: "ai-writing", description: "Synonyms, rhymes and word tools.", pricing: "free" }),
  s({ slug: "thesaurus", name: "Thesaurus.com", url: "https://www.thesaurus.com", category: "ai-writing", description: "Synonyms and antonyms reference.", pricing: "free" }),
  s({ slug: "originality-ai", name: "Originality.ai", url: "https://originality.ai", category: "ai-writing", description: "AI and plagiarism detection.", pricing: "paid" }),

  // ─────────────── AI Image & Art ───────────────
  s({ slug: "midjourney", name: "Midjourney", url: "https://www.midjourney.com", category: "ai-image", description: "High-quality AI image generation.", pricing: "paid" }),
  s({ slug: "dalle", name: "DALL·E", url: "https://openai.com/dall-e-3", category: "ai-image", description: "OpenAI's text-to-image model.", pricing: "freemium" }),
  s({ slug: "stable-diffusion", name: "Stable Diffusion", url: "https://stability.ai", category: "ai-image", description: "Open-source image generation.", pricing: "freemium" }),
  s({ slug: "leonardo-ai", name: "Leonardo AI", url: "https://leonardo.ai", category: "ai-image", description: "AI art and asset generation.", pricing: "freemium" }),
  s({ slug: "adobe-firefly", name: "Adobe Firefly", url: "https://www.adobe.com/products/firefly.html", category: "ai-image", description: "Adobe's generative image AI.", pricing: "freemium" }),
  s({ slug: "ideogram", name: "Ideogram", url: "https://ideogram.ai", category: "ai-image", description: "AI images with great typography.", pricing: "freemium" }),
  s({ slug: "recraft", name: "Recraft", url: "https://www.recraft.ai", category: "ai-image", description: "AI design and vector generation.", pricing: "freemium" }),
  s({ slug: "playground-ai", name: "Playground AI", url: "https://playground.com", category: "ai-image", description: "Free AI image creation.", pricing: "freemium" }),
  s({ slug: "nightcafe", name: "NightCafe", url: "https://creator.nightcafe.studio", category: "ai-image", description: "AI art generator community.", pricing: "freemium" }),
  s({ slug: "krea", name: "Krea", url: "https://www.krea.ai", category: "ai-image", description: "Real-time AI image and video.", pricing: "freemium" }),
  s({ slug: "magnific", name: "Magnific", url: "https://magnific.ai", category: "ai-image", description: "AI image upscaler and enhancer.", pricing: "paid" }),
  s({ slug: "freepik-ai", name: "Freepik AI", url: "https://www.freepik.com/ai", category: "ai-image", description: "AI image suite by Freepik.", pricing: "freemium" }),
  s({ slug: "bing-image-creator", name: "Bing Image Creator", url: "https://www.bing.com/images/create", category: "ai-image", description: "Free DALL·E image generation.", pricing: "free" }),
  s({ slug: "civitai", name: "Civitai", url: "https://civitai.com", category: "ai-image", description: "Stable Diffusion model hub.", pricing: "freemium" }),
  s({ slug: "lexica", name: "Lexica", url: "https://lexica.art", category: "ai-image", description: "AI art search and generation.", pricing: "freemium" }),
  s({ slug: "getimg", name: "getimg.ai", url: "https://getimg.ai", category: "ai-image", description: "AI image generation and editing.", pricing: "freemium" }),
  s({ slug: "clipdrop", name: "Clipdrop", url: "https://clipdrop.co", category: "ai-image", description: "AI image editing tools.", pricing: "freemium" }),
  s({ slug: "photoroom", name: "Photoroom", url: "https://www.photoroom.com", category: "ai-image", description: "AI background removal and editing.", pricing: "freemium" }),
  s({ slug: "remove-bg", name: "remove.bg", url: "https://www.remove.bg", category: "ai-image", description: "Remove image backgrounds instantly.", pricing: "freemium" }),
  s({ slug: "cleanup-pictures", name: "Cleanup.pictures", url: "https://cleanup.pictures", category: "ai-image", description: "Remove objects from photos.", pricing: "freemium" }),
  s({ slug: "pebblely", name: "Pebblely", url: "https://pebblely.com", category: "ai-image", description: "AI product photography.", pricing: "freemium" }),
  s({ slug: "stylar", name: "Stylar", url: "https://www.stylar.ai", category: "ai-image", description: "Controllable AI image editor.", pricing: "freemium" }),
  s({ slug: "vance-ai", name: "VanceAI", url: "https://vanceai.com", category: "ai-image", description: "AI photo enhancement suite.", pricing: "freemium" }),
  s({ slug: "lets-enhance", name: "Let's Enhance", url: "https://letsenhance.io", category: "ai-image", description: "AI image upscaling.", pricing: "freemium" }),
  s({ slug: "topaz-photo-ai", name: "Topaz Photo AI", url: "https://www.topazlabs.com", category: "ai-image", description: "Sharpen, denoise and upscale photos.", pricing: "paid" }),
  s({ slug: "pixelcut", name: "Pixelcut", url: "https://www.pixelcut.ai", category: "ai-image", description: "AI photo editor for sellers.", pricing: "freemium" }),
  s({ slug: "picsart", name: "Picsart", url: "https://picsart.com", category: "ai-image", description: "Photo editing and AI tools.", pricing: "freemium" }),
  s({ slug: "seaart", name: "SeaArt", url: "https://www.seaart.ai", category: "ai-image", description: "AI art generation platform.", pricing: "freemium" }),
  s({ slug: "tensor-art", name: "Tensor.Art", url: "https://tensor.art", category: "ai-image", description: "Free AI image models and gen.", pricing: "freemium" }),
  s({ slug: "dreamstudio", name: "DreamStudio", url: "https://dreamstudio.ai", category: "ai-image", description: "Stability AI's image studio.", pricing: "paid" }),

  // ─────────────── AI Video & Audio ───────────────
  s({ slug: "runway", name: "Runway", url: "https://runwayml.com", category: "ai-video-audio", description: "AI video generation and editing.", pricing: "freemium" }),
  s({ slug: "pika", name: "Pika", url: "https://pika.art", category: "ai-video-audio", description: "AI text-to-video generator.", pricing: "freemium" }),
  s({ slug: "luma-dream-machine", name: "Luma Dream Machine", url: "https://lumalabs.ai/dream-machine", category: "ai-video-audio", description: "AI video from text and images.", pricing: "freemium" }),
  s({ slug: "kling", name: "Kling AI", url: "https://klingai.com", category: "ai-video-audio", description: "AI video generation.", pricing: "freemium" }),
  s({ slug: "synthesia", name: "Synthesia", url: "https://www.synthesia.io", category: "ai-video-audio", description: "AI avatar video creation.", pricing: "paid" }),
  s({ slug: "heygen", name: "HeyGen", url: "https://www.heygen.com", category: "ai-video-audio", description: "AI spokesperson videos.", pricing: "freemium" }),
  s({ slug: "d-id", name: "D-ID", url: "https://www.d-id.com", category: "ai-video-audio", description: "Talking avatar videos from photos.", pricing: "freemium" }),
  s({ slug: "descript", name: "Descript", url: "https://www.descript.com", category: "ai-video-audio", description: "Edit video by editing text.", pricing: "freemium" }),
  s({ slug: "capcut", name: "CapCut", url: "https://www.capcut.com", category: "ai-video-audio", description: "Free video editor with AI.", pricing: "freemium" }),
  s({ slug: "veed", name: "VEED.IO", url: "https://www.veed.io", category: "ai-video-audio", description: "Online video editing with AI.", pricing: "freemium" }),
  s({ slug: "pictory", name: "Pictory", url: "https://pictory.ai", category: "ai-video-audio", description: "Turn scripts into videos.", pricing: "paid" }),
  s({ slug: "invideo", name: "InVideo", url: "https://invideo.io", category: "ai-video-audio", description: "AI video creation platform.", pricing: "freemium" }),
  s({ slug: "lumen5", name: "Lumen5", url: "https://lumen5.com", category: "ai-video-audio", description: "Turn blog posts into videos.", pricing: "freemium" }),
  s({ slug: "fliki", name: "Fliki", url: "https://fliki.ai", category: "ai-video-audio", description: "Text-to-video with AI voices.", pricing: "freemium" }),
  s({ slug: "kapwing", name: "Kapwing", url: "https://www.kapwing.com", category: "ai-video-audio", description: "Collaborative online video editor.", pricing: "freemium" }),
  s({ slug: "opus-clip", name: "OpusClip", url: "https://www.opus.pro", category: "ai-video-audio", description: "Turn long videos into clips.", pricing: "freemium" }),
  s({ slug: "submagic", name: "Submagic", url: "https://www.submagic.co", category: "ai-video-audio", description: "AI captions for short videos.", pricing: "paid" }),
  s({ slug: "elevenlabs", name: "ElevenLabs", url: "https://elevenlabs.io", category: "ai-video-audio", description: "Realistic AI voice generation.", pricing: "freemium" }),
  s({ slug: "murf", name: "Murf AI", url: "https://murf.ai", category: "ai-video-audio", description: "AI voiceover studio.", pricing: "freemium" }),
  s({ slug: "playht", name: "PlayHT", url: "https://play.ht", category: "ai-video-audio", description: "AI text-to-speech voices.", pricing: "freemium" }),
  s({ slug: "resemble-ai", name: "Resemble AI", url: "https://www.resemble.ai", category: "ai-video-audio", description: "AI voice cloning.", pricing: "paid" }),
  s({ slug: "suno", name: "Suno", url: "https://suno.com", category: "ai-video-audio", description: "Generate songs with AI.", pricing: "freemium" }),
  s({ slug: "udio", name: "Udio", url: "https://www.udio.com", category: "ai-video-audio", description: "AI music creation.", pricing: "freemium" }),
  s({ slug: "adobe-podcast", name: "Adobe Podcast", url: "https://podcast.adobe.com", category: "ai-video-audio", description: "AI audio enhancement.", pricing: "freemium" }),
  s({ slug: "krisp", name: "Krisp", url: "https://krisp.ai", category: "ai-video-audio", description: "AI noise cancellation.", pricing: "freemium" }),
  s({ slug: "cleanvoice", name: "Cleanvoice", url: "https://cleanvoice.ai", category: "ai-video-audio", description: "Remove filler words from audio.", pricing: "paid" }),
  s({ slug: "assemblyai", name: "AssemblyAI", url: "https://www.assemblyai.com", category: "ai-video-audio", description: "Speech-to-text API.", pricing: "paid" }),
  s({ slug: "deepgram", name: "Deepgram", url: "https://deepgram.com", category: "ai-video-audio", description: "Fast speech recognition API.", pricing: "paid" }),
  s({ slug: "otter-ai", name: "Otter.ai", url: "https://otter.ai", category: "ai-video-audio", description: "AI meeting transcription.", pricing: "freemium" }),
  s({ slug: "landr", name: "LANDR", url: "https://www.landr.com", category: "ai-video-audio", description: "AI music mastering.", pricing: "freemium" }),

  // ─────────────── Design & Creative ───────────────
  s({ slug: "canva", name: "Canva", url: "https://www.canva.com", category: "design", description: "Easy drag-and-drop design tool.", pricing: "freemium" }),
  s({ slug: "figma", name: "Figma", url: "https://www.figma.com", category: "design", description: "Collaborative interface design.", pricing: "freemium" }),
  s({ slug: "adobe-express", name: "Adobe Express", url: "https://www.adobe.com/express", category: "design", description: "Quick graphics and social content.", pricing: "freemium" }),
  s({ slug: "photoshop", name: "Adobe Photoshop", url: "https://www.adobe.com/products/photoshop.html", category: "design", description: "Industry-standard photo editor.", pricing: "paid" }),
  s({ slug: "illustrator", name: "Adobe Illustrator", url: "https://www.adobe.com/products/illustrator.html", category: "design", description: "Vector graphics design.", pricing: "paid" }),
  s({ slug: "sketch", name: "Sketch", url: "https://www.sketch.com", category: "design", description: "Mac design toolkit.", pricing: "paid" }),
  s({ slug: "framer", name: "Framer", url: "https://www.framer.com", category: "design", description: "Design and publish websites.", pricing: "freemium" }),
  s({ slug: "penpot", name: "Penpot", url: "https://penpot.app", category: "design", description: "Open-source design and prototyping.", pricing: "free" }),
  s({ slug: "photopea", name: "Photopea", url: "https://www.photopea.com", category: "design", description: "Free in-browser photo editor.", pricing: "free" }),
  s({ slug: "gimp", name: "GIMP", url: "https://www.gimp.org", category: "design", description: "Free open-source image editor.", pricing: "free" }),
  s({ slug: "krita", name: "Krita", url: "https://krita.org", category: "design", description: "Free digital painting app.", pricing: "free" }),
  s({ slug: "inkscape", name: "Inkscape", url: "https://inkscape.org", category: "design", description: "Free vector graphics editor.", pricing: "free" }),
  s({ slug: "affinity-designer", name: "Affinity Designer", url: "https://affinity.serif.com/designer", category: "design", description: "Pro vector design, one-time price.", pricing: "paid" }),
  s({ slug: "pixlr", name: "Pixlr", url: "https://pixlr.com", category: "design", description: "Online photo editor.", pricing: "freemium" }),
  s({ slug: "fotor", name: "Fotor", url: "https://www.fotor.com", category: "design", description: "Photo editing and design.", pricing: "freemium" }),
  s({ slug: "befunky", name: "BeFunky", url: "https://www.befunky.com", category: "design", description: "Photo editor and collage maker.", pricing: "freemium" }),
  s({ slug: "vistacreate", name: "VistaCreate", url: "https://create.vista.com", category: "design", description: "Graphic design made simple.", pricing: "freemium" }),
  s({ slug: "visme", name: "Visme", url: "https://www.visme.co", category: "design", description: "Presentations and infographics.", pricing: "freemium" }),
  s({ slug: "piktochart", name: "Piktochart", url: "https://piktochart.com", category: "design", description: "Infographic and report maker.", pricing: "freemium" }),
  s({ slug: "venngage", name: "Venngage", url: "https://venngage.com", category: "design", description: "Infographic design tool.", pricing: "freemium" }),
  s({ slug: "looka", name: "Looka", url: "https://looka.com", category: "design", description: "AI logo maker.", pricing: "paid" }),
  s({ slug: "brandmark", name: "Brandmark", url: "https://brandmark.io", category: "design", description: "AI logo and brand design.", pricing: "paid" }),
  s({ slug: "tailor-brands", name: "Tailor Brands", url: "https://www.tailorbrands.com", category: "design", description: "Logo and brand builder.", pricing: "paid" }),
  s({ slug: "flaticon", name: "Flaticon", url: "https://www.flaticon.com", category: "design", description: "Millions of free icons.", pricing: "freemium" }),
  s({ slug: "noun-project", name: "The Noun Project", url: "https://thenounproject.com", category: "design", description: "Icons and photos library.", pricing: "freemium" }),
  s({ slug: "iconscout", name: "Iconscout", url: "https://iconscout.com", category: "design", description: "Icons, illustrations and 3D.", pricing: "freemium" }),
  s({ slug: "undraw", name: "unDraw", url: "https://undraw.co", category: "design", description: "Free open-source illustrations.", pricing: "free" }),
  s({ slug: "storyset", name: "Storyset", url: "https://storyset.com", category: "design", description: "Customizable free illustrations.", pricing: "free" }),
  s({ slug: "lottiefiles", name: "LottieFiles", url: "https://lottiefiles.com", category: "design", description: "Lightweight animations.", pricing: "freemium" }),
  s({ slug: "coolors", name: "Coolors", url: "https://coolors.co", category: "design", description: "Color palette generator.", pricing: "freemium" }),

  // ─────────────── Stock Photos & Media ───────────────
  s({ slug: "unsplash", name: "Unsplash", url: "https://unsplash.com", category: "stock-media", description: "Free high-resolution photos.", pricing: "free" }),
  s({ slug: "pexels", name: "Pexels", url: "https://www.pexels.com", category: "stock-media", description: "Free stock photos and videos.", pricing: "free" }),
  s({ slug: "pixabay", name: "Pixabay", url: "https://pixabay.com", category: "stock-media", description: "Free images, video and music.", pricing: "free" }),
  s({ slug: "freepik", name: "Freepik", url: "https://www.freepik.com", category: "stock-media", description: "Vectors, photos and PSDs.", pricing: "freemium" }),
  s({ slug: "shutterstock", name: "Shutterstock", url: "https://www.shutterstock.com", category: "stock-media", description: "Premium stock media library.", pricing: "paid" }),
  s({ slug: "adobe-stock", name: "Adobe Stock", url: "https://stock.adobe.com", category: "stock-media", description: "Stock assets for creatives.", pricing: "paid" }),
  s({ slug: "istock", name: "iStock", url: "https://www.istockphoto.com", category: "stock-media", description: "Affordable stock by Getty.", pricing: "paid" }),
  s({ slug: "getty-images", name: "Getty Images", url: "https://www.gettyimages.com", category: "stock-media", description: "Premium editorial and stock.", pricing: "paid" }),
  s({ slug: "depositphotos", name: "Depositphotos", url: "https://depositphotos.com", category: "stock-media", description: "Royalty-free stock content.", pricing: "paid" }),
  s({ slug: "dreamstime", name: "Dreamstime", url: "https://www.dreamstime.com", category: "stock-media", description: "Stock photo community.", pricing: "freemium" }),
  s({ slug: "123rf", name: "123RF", url: "https://www.123rf.com", category: "stock-media", description: "Stock photos and vectors.", pricing: "paid" }),
  s({ slug: "vecteezy", name: "Vecteezy", url: "https://www.vecteezy.com", category: "stock-media", description: "Vectors, photos and video.", pricing: "freemium" }),
  s({ slug: "envato-elements", name: "Envato Elements", url: "https://elements.envato.com", category: "stock-media", description: "Unlimited creative assets.", pricing: "paid" }),
  s({ slug: "creative-market", name: "Creative Market", url: "https://creativemarket.com", category: "stock-media", description: "Design assets marketplace.", pricing: "paid" }),
  s({ slug: "rawpixel", name: "Rawpixel", url: "https://www.rawpixel.com", category: "stock-media", description: "Curated stock and public domain.", pricing: "freemium" }),
  s({ slug: "burst", name: "Burst", url: "https://burst.shopify.com", category: "stock-media", description: "Free photos by Shopify.", pricing: "free" }),
  s({ slug: "gratisography", name: "Gratisography", url: "https://gratisography.com", category: "stock-media", description: "Quirky free stock photos.", pricing: "free" }),
  s({ slug: "kaboompics", name: "Kaboompics", url: "https://kaboompics.com", category: "stock-media", description: "Free lifestyle photos.", pricing: "free" }),
  s({ slug: "reshot", name: "Reshot", url: "https://www.reshot.com", category: "stock-media", description: "Free icons and photos.", pricing: "free" }),
  s({ slug: "mixkit", name: "Mixkit", url: "https://mixkit.co", category: "stock-media", description: "Free video, music and SFX.", pricing: "free" }),
  s({ slug: "coverr", name: "Coverr", url: "https://coverr.co", category: "stock-media", description: "Free stock videos.", pricing: "free" }),
  s({ slug: "pond5", name: "Pond5", url: "https://www.pond5.com", category: "stock-media", description: "Video, music and SFX marketplace.", pricing: "paid" }),
  s({ slug: "artlist", name: "Artlist", url: "https://artlist.io", category: "stock-media", description: "Music and footage for creators.", pricing: "paid" }),
  s({ slug: "epidemic-sound", name: "Epidemic Sound", url: "https://www.epidemicsound.com", category: "stock-media", description: "Royalty-free music library.", pricing: "paid" }),
  s({ slug: "storyblocks", name: "Storyblocks", url: "https://www.storyblocks.com", category: "stock-media", description: "Unlimited stock media.", pricing: "paid" }),
  s({ slug: "motion-array", name: "Motion Array", url: "https://motionarray.com", category: "stock-media", description: "Video templates and assets.", pricing: "paid" }),
  s({ slug: "videvo", name: "Videvo", url: "https://www.videvo.net", category: "stock-media", description: "Free stock video and music.", pricing: "freemium" }),
  s({ slug: "free-music-archive", name: "Free Music Archive", url: "https://freemusicarchive.org", category: "stock-media", description: "Free music downloads.", pricing: "free" }),
  s({ slug: "lummi", name: "Lummi", url: "https://www.lummi.ai", category: "stock-media", description: "Free AI-generated stock photos.", pricing: "freemium" }),
  s({ slug: "openverse", name: "Openverse", url: "https://openverse.org", category: "stock-media", description: "Search open-licensed media.", pricing: "free" }),

  // ─────────────── Productivity & Docs ───────────────
  s({ slug: "notion", name: "Notion", url: "https://www.notion.so", category: "productivity", description: "All-in-one workspace for notes and docs.", pricing: "freemium" }),
  s({ slug: "google-docs", name: "Google Docs", url: "https://docs.google.com", category: "productivity", description: "Free online document editor.", pricing: "free" }),
  s({ slug: "microsoft-365", name: "Microsoft 365", url: "https://www.microsoft.com/microsoft-365", category: "productivity", description: "Word, Excel, PowerPoint online.", pricing: "paid" }),
  s({ slug: "coda", name: "Coda", url: "https://coda.io", category: "productivity", description: "Docs that work like apps.", pricing: "freemium" }),
  s({ slug: "obsidian", name: "Obsidian", url: "https://obsidian.md", category: "productivity", description: "Local-first knowledge base.", pricing: "freemium" }),
  s({ slug: "logseq", name: "Logseq", url: "https://logseq.com", category: "productivity", description: "Open-source networked notes.", pricing: "free" }),
  s({ slug: "evernote", name: "Evernote", url: "https://evernote.com", category: "productivity", description: "Note-taking and organization.", pricing: "freemium" }),
  s({ slug: "onenote", name: "OneNote", url: "https://www.onenote.com", category: "productivity", description: "Microsoft's free notebook app.", pricing: "free" }),
  s({ slug: "bear", name: "Bear", url: "https://bear.app", category: "productivity", description: "Beautiful notes for Apple devices.", pricing: "freemium" }),
  s({ slug: "craft", name: "Craft", url: "https://www.craft.do", category: "productivity", description: "Elegant documents and notes.", pricing: "freemium" }),
  s({ slug: "slite", name: "Slite", url: "https://slite.com", category: "productivity", description: "Team knowledge base.", pricing: "freemium" }),
  s({ slug: "nuclino", name: "Nuclino", url: "https://www.nuclino.com", category: "productivity", description: "Lightweight team wiki.", pricing: "freemium" }),
  s({ slug: "confluence", name: "Confluence", url: "https://www.atlassian.com/software/confluence", category: "productivity", description: "Team workspace by Atlassian.", pricing: "freemium" }),
  s({ slug: "zoho-writer", name: "Zoho Writer", url: "https://www.zoho.com/writer", category: "productivity", description: "Free online word processor.", pricing: "freemium" }),
  s({ slug: "wps-office", name: "WPS Office", url: "https://www.wps.com", category: "productivity", description: "Free office suite.", pricing: "freemium" }),
  s({ slug: "onlyoffice", name: "ONLYOFFICE", url: "https://www.onlyoffice.com", category: "productivity", description: "Open-source office suite.", pricing: "freemium" }),
  s({ slug: "libreoffice", name: "LibreOffice", url: "https://www.libreoffice.org", category: "productivity", description: "Free open-source office suite.", pricing: "free" }),
  s({ slug: "mem", name: "Mem", url: "https://get.mem.ai", category: "productivity", description: "AI-powered notes app.", pricing: "freemium" }),
  s({ slug: "reflect", name: "Reflect", url: "https://reflect.app", category: "productivity", description: "Networked note-taking.", pricing: "paid" }),
  s({ slug: "tana", name: "Tana", url: "https://tana.inc", category: "productivity", description: "AI-native workspace.", pricing: "freemium" }),
  s({ slug: "capacities", name: "Capacities", url: "https://capacities.io", category: "productivity", description: "Object-based note app.", pricing: "freemium" }),
  s({ slug: "anytype", name: "Anytype", url: "https://anytype.io", category: "productivity", description: "Local-first private workspace.", pricing: "free" }),
  s({ slug: "heptabase", name: "Heptabase", url: "https://heptabase.com", category: "productivity", description: "Visual note-taking.", pricing: "paid" }),
  s({ slug: "roam-research", name: "Roam Research", url: "https://roamresearch.com", category: "productivity", description: "Networked thought tool.", pricing: "paid" }),
  s({ slug: "dropbox-paper", name: "Dropbox Paper", url: "https://www.dropbox.com/paper", category: "productivity", description: "Collaborative documents.", pricing: "free" }),
  s({ slug: "fireflies", name: "Fireflies.ai", url: "https://fireflies.ai", category: "productivity", description: "AI meeting notetaker.", pricing: "freemium" }),
  s({ slug: "tldv", name: "tl;dv", url: "https://tldv.io", category: "productivity", description: "Record and summarize meetings.", pricing: "freemium" }),
  s({ slug: "raindrop", name: "Raindrop.io", url: "https://raindrop.io", category: "productivity", description: "All-in-one bookmark manager.", pricing: "freemium" }),
  s({ slug: "pocket", name: "Pocket", url: "https://getpocket.com", category: "productivity", description: "Save articles to read later.", pricing: "freemium" }),
  s({ slug: "todoist", name: "Todoist", url: "https://todoist.com", category: "productivity", description: "Popular to-do list app.", pricing: "freemium" }),

  // ─────────────── Project Management ───────────────
  s({ slug: "trello", name: "Trello", url: "https://trello.com", category: "project-management", description: "Kanban boards for any project.", pricing: "freemium" }),
  s({ slug: "asana", name: "Asana", url: "https://asana.com", category: "project-management", description: "Work and project management.", pricing: "freemium" }),
  s({ slug: "monday", name: "monday.com", url: "https://monday.com", category: "project-management", description: "Visual work operating system.", pricing: "paid" }),
  s({ slug: "jira", name: "Jira", url: "https://www.atlassian.com/software/jira", category: "project-management", description: "Issue tracking for software teams.", pricing: "freemium" }),
  s({ slug: "linear", name: "Linear", url: "https://linear.app", category: "project-management", description: "Fast issue tracking for product teams.", pricing: "freemium" }),
  s({ slug: "basecamp", name: "Basecamp", url: "https://basecamp.com", category: "project-management", description: "Simple project management.", pricing: "paid" }),
  s({ slug: "clickup", name: "ClickUp", url: "https://clickup.com", category: "project-management", description: "All-in-one productivity platform.", pricing: "freemium" }),
  s({ slug: "wrike", name: "Wrike", url: "https://www.wrike.com", category: "project-management", description: "Versatile work management.", pricing: "freemium" }),
  s({ slug: "smartsheet", name: "Smartsheet", url: "https://www.smartsheet.com", category: "project-management", description: "Spreadsheet-style project tool.", pricing: "paid" }),
  s({ slug: "airtable", name: "Airtable", url: "https://airtable.com", category: "project-management", description: "Database meets spreadsheet.", pricing: "freemium" }),
  s({ slug: "ticktick", name: "TickTick", url: "https://ticktick.com", category: "project-management", description: "To-do list and task manager.", pricing: "freemium" }),
  s({ slug: "microsoft-todo", name: "Microsoft To Do", url: "https://to-do.office.com", category: "project-management", description: "Free task management.", pricing: "free" }),
  s({ slug: "things", name: "Things", url: "https://culturedcode.com/things", category: "project-management", description: "Award-winning Apple task app.", pricing: "paid" }),
  s({ slug: "height", name: "Height", url: "https://height.app", category: "project-management", description: "Autonomous project management.", pricing: "freemium" }),
  s({ slug: "shortcut", name: "Shortcut", url: "https://www.shortcut.com", category: "project-management", description: "Project management for devs.", pricing: "freemium" }),
  s({ slug: "teamwork", name: "Teamwork", url: "https://www.teamwork.com", category: "project-management", description: "Client work management.", pricing: "freemium" }),
  s({ slug: "hive", name: "Hive", url: "https://hive.com", category: "project-management", description: "Project and process management.", pricing: "freemium" }),
  s({ slug: "plane", name: "Plane", url: "https://plane.so", category: "project-management", description: "Open-source project management.", pricing: "freemium" }),
  s({ slug: "taiga", name: "Taiga", url: "https://www.taiga.io", category: "project-management", description: "Open-source agile tool.", pricing: "freemium" }),
  s({ slug: "openproject", name: "OpenProject", url: "https://www.openproject.org", category: "project-management", description: "Open-source PM software.", pricing: "freemium" }),
  s({ slug: "redmine", name: "Redmine", url: "https://www.redmine.org", category: "project-management", description: "Open-source project tracker.", pricing: "free" }),
  s({ slug: "productboard", name: "Productboard", url: "https://www.productboard.com", category: "project-management", description: "Product management system.", pricing: "paid" }),
  s({ slug: "aha", name: "Aha!", url: "https://www.aha.io", category: "project-management", description: "Product roadmap software.", pricing: "paid" }),
  s({ slug: "miro", name: "Miro", url: "https://miro.com", category: "project-management", description: "Online collaborative whiteboard.", pricing: "freemium" }),
  s({ slug: "mural", name: "Mural", url: "https://www.mural.co", category: "project-management", description: "Visual collaboration workspace.", pricing: "freemium" }),
  s({ slug: "notion-projects", name: "Notion Projects", url: "https://www.notion.so/product/projects", category: "project-management", description: "Project tracking in Notion.", pricing: "freemium" }),
  s({ slug: "githubprojects", name: "GitHub Projects", url: "https://github.com/features/issues", category: "project-management", description: "Planning built into GitHub.", pricing: "freemium" }),
  s({ slug: "zenhub", name: "ZenHub", url: "https://www.zenhub.com", category: "project-management", description: "Agile PM for GitHub.", pricing: "paid" }),
  s({ slug: "nifty", name: "Nifty", url: "https://niftypm.com", category: "project-management", description: "Project management hub.", pricing: "freemium" }),
  s({ slug: "leantime", name: "Leantime", url: "https://leantime.io", category: "project-management", description: "Open-source PM for non-PMs.", pricing: "freemium" }),

  // ─────────────── PDF & File Tools ───────────────
  s({ slug: "ilovepdf", name: "iLovePDF", url: "https://www.ilovepdf.com", category: "pdf-tools", description: "Popular online PDF toolkit.", pricing: "freemium" }),
  s({ slug: "smallpdf", name: "Smallpdf", url: "https://smallpdf.com", category: "pdf-tools", description: "Simple PDF tools online.", pricing: "freemium" }),
  s({ slug: "pdf24", name: "PDF24 Tools", url: "https://tools.pdf24.org", category: "pdf-tools", description: "Free PDF tools suite.", pricing: "free" }),
  s({ slug: "sejda", name: "Sejda", url: "https://www.sejda.com", category: "pdf-tools", description: "PDF editor and tools.", pricing: "freemium" }),
  s({ slug: "stirling-pdf", name: "Stirling PDF", url: "https://www.stirlingpdf.com", category: "pdf-tools", description: "Self-hosted open-source PDF tools.", pricing: "free" }),
  s({ slug: "pdfescape", name: "PDFescape", url: "https://www.pdfescape.com", category: "pdf-tools", description: "Online PDF editor and form filler.", pricing: "freemium" }),
  s({ slug: "soda-pdf", name: "Soda PDF", url: "https://www.sodapdf.com", category: "pdf-tools", description: "PDF software and online tools.", pricing: "freemium" }),
  s({ slug: "adobe-acrobat", name: "Adobe Acrobat", url: "https://www.adobe.com/acrobat/online.html", category: "pdf-tools", description: "Official Adobe PDF tools.", pricing: "freemium" }),
  s({ slug: "foxit", name: "Foxit", url: "https://www.foxit.com", category: "pdf-tools", description: "PDF editor and reader.", pricing: "paid" }),
  s({ slug: "nitro", name: "Nitro PDF", url: "https://www.gonitro.com", category: "pdf-tools", description: "PDF productivity software.", pricing: "paid" }),
  s({ slug: "cloudconvert", name: "CloudConvert", url: "https://cloudconvert.com", category: "pdf-tools", description: "Convert between 200+ formats.", pricing: "freemium" }),
  s({ slug: "convertio", name: "Convertio", url: "https://convertio.co", category: "pdf-tools", description: "Online file converter.", pricing: "freemium" }),
  s({ slug: "zamzar", name: "Zamzar", url: "https://www.zamzar.com", category: "pdf-tools", description: "File conversion online.", pricing: "freemium" }),
  s({ slug: "freeconvert", name: "FreeConvert", url: "https://www.freeconvert.com", category: "pdf-tools", description: "Free online file converter.", pricing: "freemium" }),
  s({ slug: "online-convert", name: "Online-Convert", url: "https://www.online-convert.com", category: "pdf-tools", description: "Convert files of all types.", pricing: "freemium" }),
  s({ slug: "tinywow", name: "TinyWow", url: "https://tinywow.com", category: "pdf-tools", description: "Free PDF, image and AI tools.", pricing: "free" }),
  s({ slug: "123apps", name: "123Apps", url: "https://123apps.com", category: "pdf-tools", description: "Free web apps for media and PDF.", pricing: "free" }),
  s({ slug: "pdf-candy", name: "PDF Candy", url: "https://pdfcandy.com", category: "pdf-tools", description: "Free PDF tools and converter.", pricing: "freemium" }),
  s({ slug: "hipdf", name: "HiPDF", url: "https://www.hipdf.com", category: "pdf-tools", description: "Online PDF solution.", pricing: "freemium" }),
  s({ slug: "lightpdf", name: "LightPDF", url: "https://lightpdf.com", category: "pdf-tools", description: "Edit and convert PDFs online.", pricing: "freemium" }),
  s({ slug: "pdf2go", name: "PDF2Go", url: "https://www.pdf2go.com", category: "pdf-tools", description: "Online PDF editor and tools.", pricing: "freemium" }),
  s({ slug: "docfly", name: "DocFly", url: "https://www.docfly.com", category: "pdf-tools", description: "Online PDF editing.", pricing: "freemium" }),
  s({ slug: "xodo", name: "Xodo", url: "https://www.xodo.com", category: "pdf-tools", description: "PDF reader and editor.", pricing: "freemium" }),
  s({ slug: "deftpdf", name: "DeftPDF", url: "https://deftpdf.com", category: "pdf-tools", description: "Free online PDF tools.", pricing: "freemium" }),
  s({ slug: "combinepdf", name: "Combine PDF", url: "https://combinepdf.com", category: "pdf-tools", description: "Merge PDF files free.", pricing: "free" }),
  s({ slug: "pdfgear", name: "PDFgear", url: "https://www.pdfgear.com", category: "pdf-tools", description: "Free PDF editor with AI.", pricing: "free" }),
  s({ slug: "documentcloud", name: "DocumentCloud", url: "https://www.documentcloud.org", category: "pdf-tools", description: "Analyze and publish documents.", pricing: "free" }),
  s({ slug: "pandadoc", name: "PandaDoc", url: "https://www.pandadoc.com", category: "pdf-tools", description: "Documents and e-signatures.", pricing: "freemium" }),
  s({ slug: "docusign", name: "DocuSign", url: "https://www.docusign.com", category: "pdf-tools", description: "Electronic signature platform.", pricing: "paid" }),
  s({ slug: "dropbox-sign", name: "Dropbox Sign", url: "https://sign.dropbox.com", category: "pdf-tools", description: "E-signatures (formerly HelloSign).", pricing: "freemium" }),

  // ─────────────── Developer Platforms ───────────────
  s({ slug: "github", name: "GitHub", url: "https://github.com", category: "dev-platforms", description: "Code hosting and collaboration.", pricing: "freemium" }),
  s({ slug: "gitlab", name: "GitLab", url: "https://gitlab.com", category: "dev-platforms", description: "DevOps platform.", pricing: "freemium" }),
  s({ slug: "bitbucket", name: "Bitbucket", url: "https://bitbucket.org", category: "dev-platforms", description: "Git hosting by Atlassian.", pricing: "freemium" }),
  s({ slug: "vercel", name: "Vercel", url: "https://vercel.com", category: "dev-platforms", description: "Frontend cloud and hosting.", pricing: "freemium" }),
  s({ slug: "netlify", name: "Netlify", url: "https://www.netlify.com", category: "dev-platforms", description: "Web hosting and automation.", pricing: "freemium" }),
  s({ slug: "cloudflare-pages", name: "Cloudflare Pages", url: "https://pages.cloudflare.com", category: "dev-platforms", description: "JAMstack hosting on the edge.", pricing: "freemium" }),
  s({ slug: "render", name: "Render", url: "https://render.com", category: "dev-platforms", description: "Cloud app hosting.", pricing: "freemium" }),
  s({ slug: "railway", name: "Railway", url: "https://railway.app", category: "dev-platforms", description: "Deploy apps and databases.", pricing: "freemium" }),
  s({ slug: "fly-io", name: "Fly.io", url: "https://fly.io", category: "dev-platforms", description: "Run apps close to users.", pricing: "freemium" }),
  s({ slug: "heroku", name: "Heroku", url: "https://www.heroku.com", category: "dev-platforms", description: "Cloud application platform.", pricing: "paid" }),
  s({ slug: "aws", name: "Amazon Web Services", url: "https://aws.amazon.com", category: "dev-platforms", description: "Comprehensive cloud platform.", pricing: "freemium" }),
  s({ slug: "google-cloud", name: "Google Cloud", url: "https://cloud.google.com", category: "dev-platforms", description: "Google's cloud services.", pricing: "freemium" }),
  s({ slug: "azure", name: "Microsoft Azure", url: "https://azure.microsoft.com", category: "dev-platforms", description: "Microsoft's cloud platform.", pricing: "freemium" }),
  s({ slug: "digitalocean", name: "DigitalOcean", url: "https://www.digitalocean.com", category: "dev-platforms", description: "Developer-friendly cloud.", pricing: "paid" }),
  s({ slug: "supabase", name: "Supabase", url: "https://supabase.com", category: "dev-platforms", description: "Open-source Firebase alternative.", pricing: "freemium" }),
  s({ slug: "firebase", name: "Firebase", url: "https://firebase.google.com", category: "dev-platforms", description: "App development platform.", pricing: "freemium" }),
  s({ slug: "planetscale", name: "PlanetScale", url: "https://planetscale.com", category: "dev-platforms", description: "Serverless MySQL platform.", pricing: "paid" }),
  s({ slug: "neon", name: "Neon", url: "https://neon.tech", category: "dev-platforms", description: "Serverless Postgres.", pricing: "freemium" }),
  s({ slug: "turso", name: "Turso", url: "https://turso.tech", category: "dev-platforms", description: "Edge SQLite database.", pricing: "freemium" }),
  s({ slug: "upstash", name: "Upstash", url: "https://upstash.com", category: "dev-platforms", description: "Serverless Redis and Kafka.", pricing: "freemium" }),
  s({ slug: "mongodb-atlas", name: "MongoDB Atlas", url: "https://www.mongodb.com/atlas", category: "dev-platforms", description: "Managed MongoDB cloud.", pricing: "freemium" }),
  s({ slug: "postman", name: "Postman", url: "https://www.postman.com", category: "dev-platforms", description: "API development platform.", pricing: "freemium" }),
  s({ slug: "insomnia", name: "Insomnia", url: "https://insomnia.rest", category: "dev-platforms", description: "API client and design.", pricing: "freemium" }),
  s({ slug: "hoppscotch", name: "Hoppscotch", url: "https://hoppscotch.io", category: "dev-platforms", description: "Open-source API tester.", pricing: "free" }),
  s({ slug: "sentry", name: "Sentry", url: "https://sentry.io", category: "dev-platforms", description: "Error and performance monitoring.", pricing: "freemium" }),
  s({ slug: "replit", name: "Replit", url: "https://replit.com", category: "dev-platforms", description: "Browser-based coding IDE.", pricing: "freemium" }),
  s({ slug: "codesandbox", name: "CodeSandbox", url: "https://codesandbox.io", category: "dev-platforms", description: "Online code editor.", pricing: "freemium" }),
  s({ slug: "stackblitz", name: "StackBlitz", url: "https://stackblitz.com", category: "dev-platforms", description: "Instant dev environments.", pricing: "freemium" }),
  s({ slug: "gitpod", name: "Gitpod", url: "https://www.gitpod.io", category: "dev-platforms", description: "Cloud development environments.", pricing: "freemium" }),
  s({ slug: "cloudflare", name: "Cloudflare", url: "https://www.cloudflare.com", category: "dev-platforms", description: "CDN, security and edge compute.", pricing: "freemium" }),

  // ─────────────── No-Code & Site Builders ───────────────
  s({ slug: "webflow", name: "Webflow", url: "https://webflow.com", category: "no-code", description: "Visual website builder.", pricing: "freemium" }),
  s({ slug: "wix", name: "Wix", url: "https://www.wix.com", category: "no-code", description: "Popular website builder.", pricing: "freemium" }),
  s({ slug: "squarespace", name: "Squarespace", url: "https://www.squarespace.com", category: "no-code", description: "Websites and online stores.", pricing: "paid" }),
  s({ slug: "wordpress", name: "WordPress", url: "https://wordpress.com", category: "no-code", description: "World's most popular CMS.", pricing: "freemium" }),
  s({ slug: "ghost", name: "Ghost", url: "https://ghost.org", category: "no-code", description: "Publishing and newsletters.", pricing: "freemium" }),
  s({ slug: "carrd", name: "Carrd", url: "https://carrd.co", category: "no-code", description: "Simple one-page sites.", pricing: "freemium" }),
  s({ slug: "dorik", name: "Dorik", url: "https://dorik.com", category: "no-code", description: "No-code website builder.", pricing: "freemium" }),
  s({ slug: "softr", name: "Softr", url: "https://www.softr.io", category: "no-code", description: "Build apps from Airtable.", pricing: "freemium" }),
  s({ slug: "bubble", name: "Bubble", url: "https://bubble.io", category: "no-code", description: "Build full web apps no-code.", pricing: "freemium" }),
  s({ slug: "glide", name: "Glide", url: "https://www.glideapps.com", category: "no-code", description: "Apps from spreadsheets.", pricing: "freemium" }),
  s({ slug: "adalo", name: "Adalo", url: "https://www.adalo.com", category: "no-code", description: "No-code mobile apps.", pricing: "freemium" }),
  s({ slug: "flutterflow", name: "FlutterFlow", url: "https://flutterflow.io", category: "no-code", description: "Visual Flutter app builder.", pricing: "freemium" }),
  s({ slug: "tilda", name: "Tilda", url: "https://tilda.cc", category: "no-code", description: "Website builder for creators.", pricing: "freemium" }),
  s({ slug: "strikingly", name: "Strikingly", url: "https://www.strikingly.com", category: "no-code", description: "Simple one-page websites.", pricing: "freemium" }),
  s({ slug: "hostinger", name: "Hostinger", url: "https://www.hostinger.com", category: "no-code", description: "Web hosting and AI builder.", pricing: "paid" }),
  s({ slug: "godaddy", name: "GoDaddy", url: "https://www.godaddy.com", category: "no-code", description: "Domains and website builder.", pricing: "paid" }),
  s({ slug: "weebly", name: "Weebly", url: "https://www.weebly.com", category: "no-code", description: "Free website builder.", pricing: "freemium" }),
  s({ slug: "durable", name: "Durable", url: "https://durable.co", category: "no-code", description: "AI website builder.", pricing: "freemium" }),
  s({ slug: "10web", name: "10Web", url: "https://10web.io", category: "no-code", description: "AI-powered WordPress builder.", pricing: "paid" }),
  s({ slug: "mobirise", name: "Mobirise", url: "https://mobirise.com", category: "no-code", description: "Offline website builder.", pricing: "freemium" }),
  s({ slug: "elementor", name: "Elementor", url: "https://elementor.com", category: "no-code", description: "WordPress page builder.", pricing: "freemium" }),
  s({ slug: "divi", name: "Divi", url: "https://www.elegantthemes.com/gallery/divi", category: "no-code", description: "WordPress theme and builder.", pricing: "paid" }),
  s({ slug: "shopify", name: "Shopify", url: "https://www.shopify.com", category: "no-code", description: "Build an online store.", pricing: "paid" }),
  s({ slug: "typedream", name: "Typedream", url: "https://typedream.com", category: "no-code", description: "Notion-style site builder.", pricing: "freemium" }),
  s({ slug: "framer-sites", name: "Framer Sites", url: "https://www.framer.com/sites", category: "no-code", description: "Design and ship sites.", pricing: "freemium" }),
  s({ slug: "super", name: "Super.so", url: "https://super.so", category: "no-code", description: "Turn Notion into a website.", pricing: "paid" }),
  s({ slug: "potion", name: "Potion", url: "https://potion.so", category: "no-code", description: "Notion-based websites.", pricing: "paid" }),
  s({ slug: "popsy", name: "Popsy", url: "https://popsy.co", category: "no-code", description: "Notion-like no-code sites.", pricing: "freemium" }),
  s({ slug: "umso", name: "Umso", url: "https://www.umso.com", category: "no-code", description: "Startup website builder.", pricing: "freemium" }),
  s({ slug: "leadpages", name: "Leadpages", url: "https://www.leadpages.com", category: "no-code", description: "Landing page builder.", pricing: "paid" }),

  // ─────────────── Marketing & Email ───────────────
  s({ slug: "mailchimp", name: "Mailchimp", url: "https://mailchimp.com", category: "marketing-email", description: "Email marketing platform.", pricing: "freemium" }),
  s({ slug: "brevo", name: "Brevo", url: "https://www.brevo.com", category: "marketing-email", description: "Email, SMS and CRM (ex-Sendinblue).", pricing: "freemium" }),
  s({ slug: "convertkit", name: "Kit (ConvertKit)", url: "https://kit.com", category: "marketing-email", description: "Email marketing for creators.", pricing: "freemium" }),
  s({ slug: "activecampaign", name: "ActiveCampaign", url: "https://www.activecampaign.com", category: "marketing-email", description: "Email and marketing automation.", pricing: "paid" }),
  s({ slug: "klaviyo", name: "Klaviyo", url: "https://www.klaviyo.com", category: "marketing-email", description: "Email and SMS for e-commerce.", pricing: "freemium" }),
  s({ slug: "constant-contact", name: "Constant Contact", url: "https://www.constantcontact.com", category: "marketing-email", description: "Email marketing for SMBs.", pricing: "paid" }),
  s({ slug: "getresponse", name: "GetResponse", url: "https://www.getresponse.com", category: "marketing-email", description: "Email and automation suite.", pricing: "freemium" }),
  s({ slug: "mailerlite", name: "MailerLite", url: "https://www.mailerlite.com", category: "marketing-email", description: "Simple email marketing.", pricing: "freemium" }),
  s({ slug: "aweber", name: "AWeber", url: "https://www.aweber.com", category: "marketing-email", description: "Email marketing tools.", pricing: "freemium" }),
  s({ slug: "beehiiv", name: "beehiiv", url: "https://www.beehiiv.com", category: "marketing-email", description: "Newsletter platform.", pricing: "freemium" }),
  s({ slug: "substack", name: "Substack", url: "https://substack.com", category: "marketing-email", description: "Newsletters and paid subscriptions.", pricing: "freemium" }),
  s({ slug: "loops", name: "Loops", url: "https://loops.so", category: "marketing-email", description: "Email for SaaS companies.", pricing: "paid" }),
  s({ slug: "customer-io", name: "Customer.io", url: "https://customer.io", category: "marketing-email", description: "Automated messaging platform.", pricing: "paid" }),
  s({ slug: "hubspot", name: "HubSpot", url: "https://www.hubspot.com", category: "marketing-email", description: "CRM and marketing suite.", pricing: "freemium" }),
  s({ slug: "buffer", name: "Buffer", url: "https://buffer.com", category: "marketing-email", description: "Social media scheduling.", pricing: "freemium" }),
  s({ slug: "hootsuite", name: "Hootsuite", url: "https://www.hootsuite.com", category: "marketing-email", description: "Social media management.", pricing: "paid" }),
  s({ slug: "later", name: "Later", url: "https://later.com", category: "marketing-email", description: "Visual social scheduler.", pricing: "freemium" }),
  s({ slug: "sprout-social", name: "Sprout Social", url: "https://sproutsocial.com", category: "marketing-email", description: "Social media management.", pricing: "paid" }),
  s({ slug: "publer", name: "Publer", url: "https://publer.com", category: "marketing-email", description: "Schedule and analyze posts.", pricing: "freemium" }),
  s({ slug: "metricool", name: "Metricool", url: "https://metricool.com", category: "marketing-email", description: "Social analytics and scheduling.", pricing: "freemium" }),
  s({ slug: "socialbee", name: "SocialBee", url: "https://socialbee.com", category: "marketing-email", description: "Social media management.", pricing: "paid" }),
  s({ slug: "linktree", name: "Linktree", url: "https://linktr.ee", category: "marketing-email", description: "Link-in-bio landing page.", pricing: "freemium" }),
  s({ slug: "beacons", name: "Beacons", url: "https://beacons.ai", category: "marketing-email", description: "Link-in-bio for creators.", pricing: "freemium" }),
  s({ slug: "bitly", name: "Bitly", url: "https://bitly.com", category: "marketing-email", description: "Link shortening and tracking.", pricing: "freemium" }),
  s({ slug: "mailgun", name: "Mailgun", url: "https://www.mailgun.com", category: "marketing-email", description: "Transactional email API.", pricing: "freemium" }),
  s({ slug: "sendgrid", name: "Twilio SendGrid", url: "https://sendgrid.com", category: "marketing-email", description: "Email delivery API.", pricing: "freemium" }),
  s({ slug: "postmark", name: "Postmark", url: "https://postmarkapp.com", category: "marketing-email", description: "Fast transactional email.", pricing: "paid" }),
  s({ slug: "resend", name: "Resend", url: "https://resend.com", category: "marketing-email", description: "Email API for developers.", pricing: "freemium" }),
  s({ slug: "canva-social", name: "Canva Social", url: "https://www.canva.com/social-media", category: "marketing-email", description: "Design and schedule posts.", pricing: "freemium" }),
  s({ slug: "tailwind-app", name: "Tailwind", url: "https://www.tailwindapp.com", category: "marketing-email", description: "Pinterest and Instagram scheduling.", pricing: "freemium" }),

  // ─────────────── SEO & Analytics ───────────────
  s({ slug: "google-analytics", name: "Google Analytics", url: "https://analytics.google.com", category: "seo-analytics", description: "Free web analytics.", pricing: "free" }),
  s({ slug: "google-search-console", name: "Google Search Console", url: "https://search.google.com/search-console", category: "seo-analytics", description: "Monitor search performance.", pricing: "free" }),
  s({ slug: "ahrefs", name: "Ahrefs", url: "https://ahrefs.com", category: "seo-analytics", description: "SEO toolset and backlinks.", pricing: "paid" }),
  s({ slug: "semrush", name: "Semrush", url: "https://www.semrush.com", category: "seo-analytics", description: "All-in-one SEO platform.", pricing: "freemium" }),
  s({ slug: "moz", name: "Moz", url: "https://moz.com", category: "seo-analytics", description: "SEO software and metrics.", pricing: "freemium" }),
  s({ slug: "ubersuggest", name: "Ubersuggest", url: "https://neilpatel.com/ubersuggest", category: "seo-analytics", description: "Affordable keyword research.", pricing: "freemium" }),
  s({ slug: "screaming-frog", name: "Screaming Frog", url: "https://www.screamingfrog.co.uk", category: "seo-analytics", description: "SEO website crawler.", pricing: "freemium" }),
  s({ slug: "sitebulb", name: "Sitebulb", url: "https://sitebulb.com", category: "seo-analytics", description: "SEO audit and crawling.", pricing: "paid" }),
  s({ slug: "se-ranking", name: "SE Ranking", url: "https://seranking.com", category: "seo-analytics", description: "SEO platform for agencies.", pricing: "paid" }),
  s({ slug: "serpstat", name: "Serpstat", url: "https://serpstat.com", category: "seo-analytics", description: "SEO and PPC platform.", pricing: "freemium" }),
  s({ slug: "mangools", name: "Mangools", url: "https://mangools.com", category: "seo-analytics", description: "Easy SEO tools suite.", pricing: "paid" }),
  s({ slug: "answerthepublic", name: "AnswerThePublic", url: "https://answerthepublic.com", category: "seo-analytics", description: "Find what people search for.", pricing: "freemium" }),
  s({ slug: "alsoasked", name: "AlsoAsked", url: "https://alsoasked.com", category: "seo-analytics", description: "People Also Ask research.", pricing: "freemium" }),
  s({ slug: "keyword-tool", name: "Keyword Tool", url: "https://keywordtool.io", category: "seo-analytics", description: "Keyword ideas from autocomplete.", pricing: "freemium" }),
  s({ slug: "spyfu", name: "SpyFu", url: "https://www.spyfu.com", category: "seo-analytics", description: "Competitor keyword research.", pricing: "paid" }),
  s({ slug: "majestic", name: "Majestic", url: "https://majestic.com", category: "seo-analytics", description: "Backlink analysis.", pricing: "paid" }),
  s({ slug: "plausible", name: "Plausible", url: "https://plausible.io", category: "seo-analytics", description: "Privacy-friendly analytics.", pricing: "paid" }),
  s({ slug: "fathom", name: "Fathom Analytics", url: "https://usefathom.com", category: "seo-analytics", description: "Simple privacy analytics.", pricing: "paid" }),
  s({ slug: "matomo", name: "Matomo", url: "https://matomo.org", category: "seo-analytics", description: "Open-source analytics.", pricing: "freemium" }),
  s({ slug: "mixpanel", name: "Mixpanel", url: "https://mixpanel.com", category: "seo-analytics", description: "Product analytics.", pricing: "freemium" }),
  s({ slug: "amplitude", name: "Amplitude", url: "https://amplitude.com", category: "seo-analytics", description: "Digital analytics platform.", pricing: "freemium" }),
  s({ slug: "hotjar", name: "Hotjar", url: "https://www.hotjar.com", category: "seo-analytics", description: "Heatmaps and behavior analytics.", pricing: "freemium" }),
  s({ slug: "microsoft-clarity", name: "Microsoft Clarity", url: "https://clarity.microsoft.com", category: "seo-analytics", description: "Free heatmaps and recordings.", pricing: "free" }),
  s({ slug: "crazy-egg", name: "Crazy Egg", url: "https://www.crazyegg.com", category: "seo-analytics", description: "Website heatmaps.", pricing: "paid" }),
  s({ slug: "posthog", name: "PostHog", url: "https://posthog.com", category: "seo-analytics", description: "Open-source product analytics.", pricing: "freemium" }),
  s({ slug: "heap", name: "Heap", url: "https://www.heap.io", category: "seo-analytics", description: "Automatic event analytics.", pricing: "freemium" }),
  s({ slug: "clearscope", name: "Clearscope", url: "https://www.clearscope.io", category: "seo-analytics", description: "Content optimization.", pricing: "paid" }),
  s({ slug: "marketmuse", name: "MarketMuse", url: "https://www.marketmuse.com", category: "seo-analytics", description: "AI content planning.", pricing: "paid" }),
  s({ slug: "pagespeed-insights", name: "PageSpeed Insights", url: "https://pagespeed.web.dev", category: "seo-analytics", description: "Free page speed testing.", pricing: "free" }),
  s({ slug: "gtmetrix", name: "GTmetrix", url: "https://gtmetrix.com", category: "seo-analytics", description: "Website performance testing.", pricing: "freemium" }),

  // ─────────────── Forms & Surveys ───────────────
  s({ slug: "typeform", name: "Typeform", url: "https://www.typeform.com", category: "forms-surveys", description: "Conversational forms and surveys.", pricing: "freemium" }),
  s({ slug: "google-forms", name: "Google Forms", url: "https://forms.google.com", category: "forms-surveys", description: "Free forms and quizzes.", pricing: "free" }),
  s({ slug: "jotform", name: "Jotform", url: "https://www.jotform.com", category: "forms-surveys", description: "Powerful online form builder.", pricing: "freemium" }),
  s({ slug: "tally", name: "Tally", url: "https://tally.so", category: "forms-surveys", description: "Free flexible form builder.", pricing: "freemium" }),
  s({ slug: "microsoft-forms", name: "Microsoft Forms", url: "https://forms.office.com", category: "forms-surveys", description: "Surveys and quizzes.", pricing: "freemium" }),
  s({ slug: "surveymonkey", name: "SurveyMonkey", url: "https://www.surveymonkey.com", category: "forms-surveys", description: "Online survey platform.", pricing: "freemium" }),
  s({ slug: "formstack", name: "Formstack", url: "https://www.formstack.com", category: "forms-surveys", description: "Forms and workflow automation.", pricing: "paid" }),
  s({ slug: "wufoo", name: "Wufoo", url: "https://www.wufoo.com", category: "forms-surveys", description: "Online form builder.", pricing: "freemium" }),
  s({ slug: "paperform", name: "Paperform", url: "https://paperform.co", category: "forms-surveys", description: "Forms, surveys and payments.", pricing: "paid" }),
  s({ slug: "cognito-forms", name: "Cognito Forms", url: "https://www.cognitoforms.com", category: "forms-surveys", description: "Advanced free forms.", pricing: "freemium" }),
  s({ slug: "fillout", name: "Fillout", url: "https://www.fillout.com", category: "forms-surveys", description: "Powerful free forms.", pricing: "freemium" }),
  s({ slug: "forms-app", name: "forms.app", url: "https://forms.app", category: "forms-surveys", description: "Online form and survey maker.", pricing: "freemium" }),
  s({ slug: "zoho-survey", name: "Zoho Survey", url: "https://www.zoho.com/survey", category: "forms-surveys", description: "Online survey software.", pricing: "freemium" }),
  s({ slug: "qualtrics", name: "Qualtrics", url: "https://www.qualtrics.com", category: "forms-surveys", description: "Experience management surveys.", pricing: "paid" }),
  s({ slug: "alchemer", name: "Alchemer", url: "https://www.alchemer.com", category: "forms-surveys", description: "Enterprise survey platform.", pricing: "paid" }),
  s({ slug: "formspree", name: "Formspree", url: "https://formspree.io", category: "forms-surveys", description: "Form backend for developers.", pricing: "freemium" }),
  s({ slug: "getform", name: "Getform", url: "https://getform.io", category: "forms-surveys", description: "Form endpoints for static sites.", pricing: "freemium" }),
  s({ slug: "basin", name: "Basin", url: "https://usebasin.com", category: "forms-surveys", description: "Form backend service.", pricing: "freemium" }),
  s({ slug: "formcarry", name: "Formcarry", url: "https://formcarry.com", category: "forms-surveys", description: "Form submission backend.", pricing: "freemium" }),
  s({ slug: "heyform", name: "HeyForm", url: "https://heyform.net", category: "forms-surveys", description: "Open-source form builder.", pricing: "freemium" }),
  s({ slug: "feathery", name: "Feathery", url: "https://feathery.io", category: "forms-surveys", description: "Developer-friendly forms.", pricing: "freemium" }),
  s({ slug: "youform", name: "Youform", url: "https://youform.com", category: "forms-surveys", description: "Unlimited free forms.", pricing: "freemium" }),
  s({ slug: "formbricks", name: "Formbricks", url: "https://formbricks.com", category: "forms-surveys", description: "Open-source survey platform.", pricing: "freemium" }),
  s({ slug: "surveysparrow", name: "SurveySparrow", url: "https://surveysparrow.com", category: "forms-surveys", description: "Conversational surveys.", pricing: "freemium" }),
  s({ slug: "pollunit", name: "PollUnit", url: "https://pollunit.com", category: "forms-surveys", description: "Polls and group decisions.", pricing: "freemium" }),
  s({ slug: "strawpoll", name: "StrawPoll", url: "https://strawpoll.com", category: "forms-surveys", description: "Quick free online polls.", pricing: "free" }),
  s({ slug: "mentimeter", name: "Mentimeter", url: "https://www.mentimeter.com", category: "forms-surveys", description: "Interactive presentations and polls.", pricing: "freemium" }),
  s({ slug: "slido", name: "Slido", url: "https://www.slido.com", category: "forms-surveys", description: "Audience Q&A and polls.", pricing: "freemium" }),
  s({ slug: "involve-me", name: "involve.me", url: "https://www.involve.me", category: "forms-surveys", description: "Interactive funnels and forms.", pricing: "freemium" }),
  s({ slug: "yesinsights", name: "YesInsights", url: "https://www.yesinsights.com", category: "forms-surveys", description: "One-click surveys.", pricing: "paid" }),

  // ─────────────── Scheduling & Communication ───────────────
  s({ slug: "calendly", name: "Calendly", url: "https://calendly.com", category: "scheduling-comms", description: "Automated scheduling.", pricing: "freemium" }),
  s({ slug: "cal-com", name: "Cal.com", url: "https://cal.com", category: "scheduling-comms", description: "Open-source scheduling.", pricing: "freemium" }),
  s({ slug: "savvycal", name: "SavvyCal", url: "https://savvycal.com", category: "scheduling-comms", description: "Friendly scheduling tool.", pricing: "paid" }),
  s({ slug: "doodle", name: "Doodle", url: "https://doodle.com", category: "scheduling-comms", description: "Group meeting polls.", pricing: "freemium" }),
  s({ slug: "acuity", name: "Acuity Scheduling", url: "https://www.acuityscheduling.com", category: "scheduling-comms", description: "Appointment scheduling.", pricing: "paid" }),
  s({ slug: "zoom", name: "Zoom", url: "https://zoom.us", category: "scheduling-comms", description: "Video meetings and webinars.", pricing: "freemium" }),
  s({ slug: "google-meet", name: "Google Meet", url: "https://meet.google.com", category: "scheduling-comms", description: "Free video conferencing.", pricing: "freemium" }),
  s({ slug: "microsoft-teams", name: "Microsoft Teams", url: "https://www.microsoft.com/microsoft-teams", category: "scheduling-comms", description: "Chat and meetings.", pricing: "freemium" }),
  s({ slug: "slack", name: "Slack", url: "https://slack.com", category: "scheduling-comms", description: "Team messaging.", pricing: "freemium" }),
  s({ slug: "discord", name: "Discord", url: "https://discord.com", category: "scheduling-comms", description: "Community chat and voice.", pricing: "freemium" }),
  s({ slug: "webex", name: "Webex", url: "https://www.webex.com", category: "scheduling-comms", description: "Video conferencing by Cisco.", pricing: "freemium" }),
  s({ slug: "whereby", name: "Whereby", url: "https://whereby.com", category: "scheduling-comms", description: "Browser-based video calls.", pricing: "freemium" }),
  s({ slug: "loom", name: "Loom", url: "https://www.loom.com", category: "scheduling-comms", description: "Async video messaging.", pricing: "freemium" }),
  s({ slug: "twilio", name: "Twilio", url: "https://www.twilio.com", category: "scheduling-comms", description: "SMS, voice and messaging API.", pricing: "paid" }),
  s({ slug: "ringcentral", name: "RingCentral", url: "https://www.ringcentral.com", category: "scheduling-comms", description: "Cloud phone system.", pricing: "paid" }),
  s({ slug: "aircall", name: "Aircall", url: "https://aircall.io", category: "scheduling-comms", description: "Cloud-based call center.", pricing: "paid" }),
  s({ slug: "dialpad", name: "Dialpad", url: "https://www.dialpad.com", category: "scheduling-comms", description: "AI-powered business phone.", pricing: "paid" }),
  s({ slug: "openphone", name: "OpenPhone", url: "https://www.openphone.com", category: "scheduling-comms", description: "Business phone for teams.", pricing: "paid" }),
  s({ slug: "intercom", name: "Intercom", url: "https://www.intercom.com", category: "scheduling-comms", description: "Customer messaging platform.", pricing: "paid" }),
  s({ slug: "crisp", name: "Crisp", url: "https://crisp.chat", category: "scheduling-comms", description: "Customer messaging and chat.", pricing: "freemium" }),
  s({ slug: "tawk-to", name: "Tawk.to", url: "https://www.tawk.to", category: "scheduling-comms", description: "Free live chat software.", pricing: "free" }),
  s({ slug: "zendesk", name: "Zendesk", url: "https://www.zendesk.com", category: "scheduling-comms", description: "Customer support platform.", pricing: "paid" }),
  s({ slug: "front", name: "Front", url: "https://front.com", category: "scheduling-comms", description: "Shared inbox for teams.", pricing: "paid" }),
  s({ slug: "tidio", name: "Tidio", url: "https://www.tidio.com", category: "scheduling-comms", description: "Live chat and chatbots.", pricing: "freemium" }),
  s({ slug: "google-calendar", name: "Google Calendar", url: "https://calendar.google.com", category: "scheduling-comms", description: "Free calendar and scheduling.", pricing: "free" }),
  s({ slug: "fantastical", name: "Fantastical", url: "https://flexibits.com/fantastical", category: "scheduling-comms", description: "Calendar app for Apple.", pricing: "freemium" }),
  s({ slug: "motion", name: "Motion", url: "https://www.usemotion.com", category: "scheduling-comms", description: "AI calendar and task planner.", pricing: "paid" }),
  s({ slug: "reclaim", name: "Reclaim.ai", url: "https://reclaim.ai", category: "scheduling-comms", description: "AI scheduling for calendars.", pricing: "freemium" }),
  s({ slug: "youcanbookme", name: "YouCanBookMe", url: "https://youcanbook.me", category: "scheduling-comms", description: "Online booking pages.", pricing: "freemium" }),
  s({ slug: "chili-piper", name: "Chili Piper", url: "https://www.chilipiper.com", category: "scheduling-comms", description: "Scheduling for sales teams.", pricing: "paid" }),

  // ─────────────── Storage & File Sharing ───────────────
  s({ slug: "google-drive", name: "Google Drive", url: "https://drive.google.com", category: "storage-sharing", description: "Cloud storage by Google.", pricing: "freemium" }),
  s({ slug: "dropbox", name: "Dropbox", url: "https://www.dropbox.com", category: "storage-sharing", description: "File storage and sync.", pricing: "freemium" }),
  s({ slug: "onedrive", name: "OneDrive", url: "https://onedrive.live.com", category: "storage-sharing", description: "Microsoft cloud storage.", pricing: "freemium" }),
  s({ slug: "box", name: "Box", url: "https://www.box.com", category: "storage-sharing", description: "Cloud content management.", pricing: "freemium" }),
  s({ slug: "icloud", name: "iCloud", url: "https://www.icloud.com", category: "storage-sharing", description: "Apple cloud storage.", pricing: "freemium" }),
  s({ slug: "pcloud", name: "pCloud", url: "https://www.pcloud.com", category: "storage-sharing", description: "Secure cloud storage.", pricing: "freemium" }),
  s({ slug: "mega", name: "MEGA", url: "https://mega.io", category: "storage-sharing", description: "Encrypted cloud storage.", pricing: "freemium" }),
  s({ slug: "sync-com", name: "Sync.com", url: "https://www.sync.com", category: "storage-sharing", description: "Private cloud storage.", pricing: "freemium" }),
  s({ slug: "icedrive", name: "Icedrive", url: "https://icedrive.net", category: "storage-sharing", description: "Encrypted cloud drive.", pricing: "freemium" }),
  s({ slug: "backblaze", name: "Backblaze", url: "https://www.backblaze.com", category: "storage-sharing", description: "Backup and B2 cloud storage.", pricing: "paid" }),
  s({ slug: "wetransfer", name: "WeTransfer", url: "https://wetransfer.com", category: "storage-sharing", description: "Send large files free.", pricing: "freemium" }),
  s({ slug: "smash", name: "Smash", url: "https://fromsmash.com", category: "storage-sharing", description: "Transfer files of any size.", pricing: "freemium" }),
  s({ slug: "filemail", name: "Filemail", url: "https://www.filemail.com", category: "storage-sharing", description: "Send big files fast.", pricing: "freemium" }),
  s({ slug: "send-anywhere", name: "Send Anywhere", url: "https://send-anywhere.com", category: "storage-sharing", description: "Cross-platform file transfer.", pricing: "freemium" }),
  s({ slug: "tresorit", name: "Tresorit", url: "https://tresorit.com", category: "storage-sharing", description: "End-to-end encrypted storage.", pricing: "paid" }),
  s({ slug: "internxt", name: "Internxt", url: "https://internxt.com", category: "storage-sharing", description: "Open-source encrypted storage.", pricing: "freemium" }),
  s({ slug: "proton-drive", name: "Proton Drive", url: "https://proton.me/drive", category: "storage-sharing", description: "Encrypted cloud storage.", pricing: "freemium" }),
  s({ slug: "wormhole", name: "Wormhole", url: "https://wormhole.app", category: "storage-sharing", description: "Encrypted file sharing.", pricing: "free" }),
  s({ slug: "file-io", name: "File.io", url: "https://www.file.io", category: "storage-sharing", description: "Ephemeral file sharing.", pricing: "freemium" }),
  s({ slug: "gofile", name: "Gofile", url: "https://gofile.io", category: "storage-sharing", description: "Free unlimited file sharing.", pricing: "free" }),
  s({ slug: "mediafire", name: "MediaFire", url: "https://www.mediafire.com", category: "storage-sharing", description: "File hosting and sharing.", pricing: "freemium" }),
  s({ slug: "jumpshare", name: "Jumpshare", url: "https://jumpshare.com", category: "storage-sharing", description: "Share files and screen recordings.", pricing: "freemium" }),
  s({ slug: "transfernow", name: "TransferNow", url: "https://www.transfernow.net", category: "storage-sharing", description: "Send large files securely.", pricing: "freemium" }),
  s({ slug: "nextcloud", name: "Nextcloud", url: "https://nextcloud.com", category: "storage-sharing", description: "Self-hosted file platform.", pricing: "freemium" }),
  s({ slug: "amazon-s3", name: "Amazon S3", url: "https://aws.amazon.com/s3", category: "storage-sharing", description: "Object storage at scale.", pricing: "paid" }),
  s({ slug: "cloudflare-r2", name: "Cloudflare R2", url: "https://www.cloudflare.com/products/r2", category: "storage-sharing", description: "Object storage, no egress fees.", pricing: "freemium" }),
  s({ slug: "wasabi", name: "Wasabi", url: "https://wasabi.com", category: "storage-sharing", description: "Hot cloud storage.", pricing: "paid" }),
  s({ slug: "degoo", name: "Degoo", url: "https://degoo.com", category: "storage-sharing", description: "Cloud backup storage.", pricing: "freemium" }),
  s({ slug: "koofr", name: "Koofr", url: "https://koofr.eu", category: "storage-sharing", description: "EU-based cloud storage.", pricing: "freemium" }),
  s({ slug: "filen", name: "Filen", url: "https://filen.io", category: "storage-sharing", description: "Zero-knowledge cloud storage.", pricing: "freemium" }),

  // ─────────────── Finance & Commerce ───────────────
  s({ slug: "stripe", name: "Stripe", url: "https://stripe.com", category: "finance-commerce", description: "Payments infrastructure.", pricing: "paid" }),
  s({ slug: "paypal", name: "PayPal", url: "https://www.paypal.com", category: "finance-commerce", description: "Online payments.", pricing: "freemium" }),
  s({ slug: "wise", name: "Wise", url: "https://wise.com", category: "finance-commerce", description: "Low-cost international transfers.", pricing: "paid" }),
  s({ slug: "square", name: "Square", url: "https://squareup.com", category: "finance-commerce", description: "Payments and POS.", pricing: "freemium" }),
  s({ slug: "razorpay", name: "Razorpay", url: "https://razorpay.com", category: "finance-commerce", description: "Payments for India.", pricing: "paid" }),
  s({ slug: "paddle", name: "Paddle", url: "https://www.paddle.com", category: "finance-commerce", description: "Merchant of record for SaaS.", pricing: "paid" }),
  s({ slug: "lemon-squeezy", name: "Lemon Squeezy", url: "https://www.lemonsqueezy.com", category: "finance-commerce", description: "Sell digital products easily.", pricing: "paid" }),
  s({ slug: "gumroad", name: "Gumroad", url: "https://gumroad.com", category: "finance-commerce", description: "Sell digital products.", pricing: "paid" }),
  s({ slug: "woocommerce", name: "WooCommerce", url: "https://woocommerce.com", category: "finance-commerce", description: "WordPress e-commerce.", pricing: "freemium" }),
  s({ slug: "bigcommerce", name: "BigCommerce", url: "https://www.bigcommerce.com", category: "finance-commerce", description: "E-commerce platform.", pricing: "paid" }),
  s({ slug: "etsy", name: "Etsy", url: "https://www.etsy.com", category: "finance-commerce", description: "Marketplace for handmade goods.", pricing: "paid" }),
  s({ slug: "quickbooks", name: "QuickBooks", url: "https://quickbooks.intuit.com", category: "finance-commerce", description: "Accounting for small business.", pricing: "paid" }),
  s({ slug: "xero", name: "Xero", url: "https://www.xero.com", category: "finance-commerce", description: "Cloud accounting software.", pricing: "paid" }),
  s({ slug: "freshbooks", name: "FreshBooks", url: "https://www.freshbooks.com", category: "finance-commerce", description: "Invoicing and accounting.", pricing: "paid" }),
  s({ slug: "wave", name: "Wave", url: "https://www.waveapps.com", category: "finance-commerce", description: "Free accounting and invoicing.", pricing: "freemium" }),
  s({ slug: "zoho-books", name: "Zoho Books", url: "https://www.zoho.com/books", category: "finance-commerce", description: "Online accounting software.", pricing: "freemium" }),
  s({ slug: "expensify", name: "Expensify", url: "https://www.expensify.com", category: "finance-commerce", description: "Expense management.", pricing: "freemium" }),
  s({ slug: "ramp", name: "Ramp", url: "https://ramp.com", category: "finance-commerce", description: "Corporate cards and spend.", pricing: "free" }),
  s({ slug: "brex", name: "Brex", url: "https://www.brex.com", category: "finance-commerce", description: "Corporate cards and finance.", pricing: "freemium" }),
  s({ slug: "mercury", name: "Mercury", url: "https://mercury.com", category: "finance-commerce", description: "Banking for startups.", pricing: "free" }),
  s({ slug: "revolut", name: "Revolut", url: "https://www.revolut.com", category: "finance-commerce", description: "Digital banking app.", pricing: "freemium" }),
  s({ slug: "payoneer", name: "Payoneer", url: "https://www.payoneer.com", category: "finance-commerce", description: "Global payments for businesses.", pricing: "paid" }),
  s({ slug: "deel", name: "Deel", url: "https://www.deel.com", category: "finance-commerce", description: "Global payroll and hiring.", pricing: "paid" }),
  s({ slug: "remote", name: "Remote", url: "https://remote.com", category: "finance-commerce", description: "Hire and pay globally.", pricing: "paid" }),
  s({ slug: "gusto", name: "Gusto", url: "https://gusto.com", category: "finance-commerce", description: "Payroll and benefits.", pricing: "paid" }),
  s({ slug: "rippling", name: "Rippling", url: "https://www.rippling.com", category: "finance-commerce", description: "HR, IT and finance platform.", pricing: "paid" }),
  s({ slug: "bill-com", name: "BILL", url: "https://www.bill.com", category: "finance-commerce", description: "Accounts payable automation.", pricing: "paid" }),
  s({ slug: "invoice-ninja", name: "Invoice Ninja", url: "https://www.invoiceninja.com", category: "finance-commerce", description: "Open-source invoicing.", pricing: "freemium" }),
  s({ slug: "chargebee", name: "Chargebee", url: "https://www.chargebee.com", category: "finance-commerce", description: "Subscription billing.", pricing: "freemium" }),
  s({ slug: "polar", name: "Polar", url: "https://polar.sh", category: "finance-commerce", description: "Monetization for developers.", pricing: "paid" }),
];

// ───────────────────────────── helpers ─────────────────────────────

const serviceBySlug = new Map<string, Service>(services.map((svc) => [svc.slug, svc]));
const serviceCategoryBySlug = new Map<string, ServiceCategory>(
  serviceCategories.map((c) => [c.slug, c])
);

export function getService(slug: string): Service | undefined {
  return serviceBySlug.get(slug);
}

export function getServiceCategory(slug: string): ServiceCategory | undefined {
  return serviceCategoryBySlug.get(slug);
}

export function getServicesByCategory(categorySlug: string): Service[] {
  return services.filter((svc) => svc.category === categorySlug);
}

export function getServiceCount(categorySlug: string): number {
  return getServicesByCategory(categorySlug).length;
}

export const SERVICE_COUNT = services.length;
